package com.mir.payhub.activity.enums;

public enum ActivityType {
    LOGIN,
    PROFILE_UPDATED,
    VERIFICATION_STARTED,
    ACCOUNT_CREATED,
    ACCOUNT_CREATION_FAILED,
    BENEFICIARY_ADDED,
    BENEFICIARY_UPDATED,
    BENEFICIARY_DEACTIVATED,
    TRANSFER_CREATED,
    TRANSFER_COMPLETED,
    TRANSFER_FAILED
}
