spring:
  application:
    name: payhub-backend

  profiles:
    active: local

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    root: INFO

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      access-token-expiration: 900000
      refresh-token-expiration: 604800000
